#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7
ENV_FILE="${PROSEPECT_DEPLOY_ENV:-.env.deploy}"

require_value() {
  local name="$1" value="$2"
  if [[ -z "$value" ]]; then
    warn "$name is required."
    exit 1
  fi
}

banner "Prosepect free hosted deployment"

stage "Neon PostgreSQL"
say "Neon stores canonical product data, synchronization jobs, conflicts, and activity."
open_url "https://console.neon.tech/app/projects"
step "Create a project named prosepect in a region close to Singapore."
step "Open Connect, select the direct connection rather than the pooled connection, and require TLS."
ask_secret DATABASE_URL "Paste the direct PostgreSQL connection string:"
if [[ "$DATABASE_URL" != postgres://* && "$DATABASE_URL" != postgresql://* ]]; then
  warn "The connection string does not look like a PostgreSQL URL."
  exit 1
fi
write_env DATABASE_URL "$DATABASE_URL"
chmod 600 "$ENV_FILE"

stage "Cloudflare R2 attachments"
say "R2 stores private attachment bytes. Stop here if Cloudflare requests a payment authorization you do not accept."
open_url "https://dash.cloudflare.com/?to=/:account/r2/overview"
step "Create a private bucket named prosepect."
step "Open Manage R2 API Tokens and create an Object Read & Write token restricted to that bucket."
ask S3_BUCKET "R2 bucket name [prosepect]:"
S3_BUCKET="${S3_BUCKET:-prosepect}"
ask S3_ENDPOINT "R2 S3 endpoint, such as https://ACCOUNT_ID.r2.cloudflarestorage.com:"
ask_secret S3_ACCESS_KEY_ID "R2 Access Key ID:"
ask_secret S3_SECRET_ACCESS_KEY "R2 Secret Access Key:"
require_value S3_ENDPOINT "$S3_ENDPOINT"
require_value S3_ACCESS_KEY_ID "$S3_ACCESS_KEY_ID"
require_value S3_SECRET_ACCESS_KEY "$S3_SECRET_ACCESS_KEY"
write_env S3_BUCKET "$S3_BUCKET"
write_env S3_ENDPOINT "$S3_ENDPOINT"
write_env S3_PUBLIC_ENDPOINT "$S3_ENDPOINT"
write_env S3_ACCESS_KEY_ID "$S3_ACCESS_KEY_ID"
write_env S3_SECRET_ACCESS_KEY "$S3_SECRET_ACCESS_KEY"
chmod 600 "$ENV_FILE"

stage "Google OAuth and Calendar"
say "Google OAuth provides login and optional incremental Calendar consent. This setup does not enable paid Google Cloud services."
ask GCP_PROJECT_ID "Google Cloud Project ID [prosepect]:"
GCP_PROJECT_ID="${GCP_PROJECT_ID:-prosepect}"
open_url "https://console.cloud.google.com/apis/library/calendar-json.googleapis.com?project=${GCP_PROJECT_ID}"
step "Enable the Google Calendar API."
open_url "https://console.cloud.google.com/auth/overview?project=${GCP_PROJECT_ID}"
step "Configure the OAuth consent screen and add your Google account as a test user if the app remains in testing."
open_url "https://console.cloud.google.com/auth/clients?project=${GCP_PROJECT_ID}"
step "Create a Web application client named Prosepect."
step "Add https://prosepect.com as an authorized JavaScript origin."
step "Add https://api.prosepect.com/api/v1/auth/google/callback as an authorized redirect URI."
ask GOOGLE_CLIENT_ID "Google OAuth Client ID:"
ask_secret GOOGLE_CLIENT_SECRET "Google OAuth Client Secret:"
require_value GOOGLE_CLIENT_ID "$GOOGLE_CLIENT_ID"
require_value GOOGLE_CLIENT_SECRET "$GOOGLE_CLIENT_SECRET"
TOKEN_ENCRYPTION_KEY=$(_existing TOKEN_ENCRYPTION_KEY || true)
if [[ -z "$TOKEN_ENCRYPTION_KEY" ]]; then
  TOKEN_ENCRYPTION_KEY=$(openssl rand -base64 32)
fi
ask INVITE_EMAIL "Google account email to invite:"
require_value INVITE_EMAIL "$INVITE_EMAIL"
write_env GCP_PROJECT_ID "$GCP_PROJECT_ID"
write_env GOOGLE_CLIENT_ID "$GOOGLE_CLIENT_ID"
write_env GOOGLE_CLIENT_SECRET "$GOOGLE_CLIENT_SECRET"
write_env TOKEN_ENCRYPTION_KEY "$TOKEN_ENCRYPTION_KEY"
write_env INVITE_EMAIL "$INVITE_EMAIL"
chmod 600 "$ENV_FILE"

stage "Render Free API"
say "Render builds the reviewed Dockerfile and runs one free web-service instance. It sleeps after 15 idle minutes and can take about one minute to wake."
if [[ -n "$(git status --porcelain)" ]]; then
  warn "The repository is not clean. Commit and push the reviewed deployment files before creating the Blueprint."
  exit 1
fi
open_url "https://render.com/deploy?repo=https://github.com/danarrigo/prosepect"
step "Connect GitHub, select the main branch, and create the prosepect-api Blueprint on the Free plan."
step "For each requested secret, paste the matching value from ${ENV_FILE}: DATABASE_URL, GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, TOKEN_ENCRYPTION_KEY, S3_BUCKET, S3_ENDPOINT, S3_PUBLIC_ENDPOINT, S3_ACCESS_KEY_ID, and S3_SECRET_ACCESS_KEY."
step "Wait for the initial Docker build and deployment to finish."
pause "Press Enter after Render reports that prosepect-api is live."
ask RENDER_API_URL "Render service URL, such as https://prosepect-api.onrender.com:"
RENDER_API_URL="${RENDER_API_URL%/}"
require_value RENDER_API_URL "$RENDER_API_URL"
write_env RENDER_API_URL "$RENDER_API_URL"
if ! curl --fail --silent --show-error --max-time 90 "${RENDER_API_URL}/ready" >/dev/null; then
  warn "The Render readiness check failed. Inspect the service logs before continuing."
  exit 1
fi
say "Render readiness passed."

stage "Scheduled synchronization worker"
say "GitHub Actions runs prosepect-worker --once every 15 minutes. Scheduled public-repository runners are free but can be delayed."
set_secret PROSEPECT_DATABASE_URL "$DATABASE_URL"
set_secret PROSEPECT_GOOGLE_CLIENT_ID "$GOOGLE_CLIENT_ID"
set_secret PROSEPECT_GOOGLE_CLIENT_SECRET "$GOOGLE_CLIENT_SECRET"
set_secret PROSEPECT_TOKEN_ENCRYPTION_KEY "$TOKEN_ENCRYPTION_KEY"
set_secret PROSEPECT_S3_BUCKET "$S3_BUCKET"
set_secret PROSEPECT_S3_ENDPOINT "$S3_ENDPOINT"
set_secret PROSEPECT_S3_ACCESS_KEY_ID "$S3_ACCESS_KEY_ID"
set_secret PROSEPECT_S3_SECRET_ACCESS_KEY "$S3_SECRET_ACCESS_KEY"
set_var PROSEPECT_WORKER_ENABLED "true"
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  gh workflow run worker.yml
  say "Started the first synchronization worker run."
else
  warn "Run 'gh workflow run worker.yml' after GitHub CLI authentication is restored."
fi

stage "Domains and Vercel"
say "Attach api.prosepect.com to Render, then deploy the SPA at prosepect.com."
open_url "https://dashboard.render.com"
step "Open prosepect-api, then Settings and Custom Domains. Add api.prosepect.com."
step "Add the DNS record Render displays and wait for its TLS certificate."
open_url "https://vercel.com/new/clone?repository-url=https://github.com/danarrigo/prosepect"
step "Import the repository with apps/web as Root Directory and enable including files outside the root."
step "Set VITE_API_URL to https://api.prosepect.com for Production."
step "Deploy, attach prosepect.com, and add the DNS records Vercel displays."
pause "Press Enter when Render, Vercel, and DNS are configured."

stage "Invite and verify"
say "The API migrations create the invite table before the first sign-in."
for attempt in $(seq 1 40); do
  if curl --fail --silent "https://api.prosepect.com/ready" >/dev/null; then
    break
  fi
  sleep 15
done
curl --fail --silent "https://api.prosepect.com/ready" >/dev/null
if command -v psql >/dev/null 2>&1; then
  psql "$DATABASE_URL" --set ON_ERROR_STOP=1 --set invite_email="$INVITE_EMAIL" <<'SQL'
INSERT INTO account_invites (id, email)
VALUES (gen_random_uuid(), LOWER(:'invite_email'))
ON CONFLICT (email) DO NOTHING;
SQL
else
  warn "psql is unavailable. Add the invite through the Neon SQL editor."
fi
open_url "https://prosepect.com"
step "Sign in with ${INVITE_EMAIL}."
step "Create a task and event, upload and download an attachment, then connect Google Calendar."
step "Check Render logs and the latest Synchronization worker workflow for errors."
pause "Press Enter after the production smoke test passes."

finish
