#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9
ENV_FILE="${PROSEPECT_DEPLOY_ENV:-.env.deploy}"

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    warn "$1 is required but is not installed."
    return 1
  fi
}

upsert_google_secret() {
  local name="$1" value="$2"
  if gcloud secrets describe "$name" --project "$GCP_PROJECT_ID" >/dev/null 2>&1; then
    printf '%s' "$value" | gcloud secrets versions add "$name" \
      --project "$GCP_PROJECT_ID" --data-file=- >/dev/null
  else
    printf '%s' "$value" | gcloud secrets create "$name" \
      --project "$GCP_PROJECT_ID" --replication-policy=automatic --data-file=- >/dev/null
  fi
  gcloud secrets add-iam-policy-binding "$name" \
    --project "$GCP_PROJECT_ID" \
    --member "serviceAccount:prosepect-runtime@${GCP_PROJECT_ID}.iam.gserviceaccount.com" \
    --role roles/secretmanager.secretAccessor >/dev/null
  printf '  %s✓ configured%s Google secret %s\n' "$GREEN" "$RESET" "$name"
}

banner "Prosepect free hosted deployment"

stage "Google Cloud project"
say "Choose the Google Cloud project that will run Prosepect. Billing must be enabled, but the deployment is constrained for the free allowances."
open_url "https://console.cloud.google.com/projectselector2/home/dashboard"
step "Create or select a project and copy its immutable Project ID, not its display name."
ask GCP_PROJECT_ID "Google Cloud Project ID:"
ask GCP_REGION "Cloud Run region [asia-southeast1]:"
GCP_REGION="${GCP_REGION:-asia-southeast1}"
write_env GCP_PROJECT_ID "$GCP_PROJECT_ID"
write_env GCP_REGION "$GCP_REGION"
chmod 600 "$ENV_FILE"
open_url "https://console.cloud.google.com/billing/linkedaccount?project=${GCP_PROJECT_ID}"
step "Link a billing account to the project and configure a small billing budget alert."
pause "Press Enter after billing is enabled."
if ! require_command gcloud || ! timeout 20s gcloud --version >/dev/null 2>&1; then
  warn "The current gcloud installation is unavailable from WSL."
  open_url "https://cloud.google.com/sdk/docs/install-sdk#linux"
  step "Install the Linux x86_64 Google Cloud CLI inside WSL, then restart this wizard."
  exit 1
fi
if [[ -z "$(gcloud auth list --filter=status:ACTIVE --format='value(account)' 2>/dev/null)" ]]; then
  gcloud auth login
fi
gcloud config set project "$GCP_PROJECT_ID" >/dev/null
gcloud config set run/region "$GCP_REGION" >/dev/null

stage "Neon PostgreSQL"
say "Neon supplies the free PostgreSQL database. Use a region geographically close to Cloud Run."
open_url "https://console.neon.tech/app/projects"
step "Create a project named prosepect."
step "Open Connect, select the direct connection rather than the pooled connection, and require TLS."
ask_secret DATABASE_URL "Paste the direct PostgreSQL connection string:"
if [[ "$DATABASE_URL" != postgres://* && "$DATABASE_URL" != postgresql://* ]]; then
  warn "The connection string does not look like a PostgreSQL URL."
  exit 1
fi
write_env DATABASE_URL "$DATABASE_URL"
chmod 600 "$ENV_FILE"

stage "Cloudflare R2 attachments"
say "R2 supplies private S3-compatible attachment storage within its free allowance."
open_url "https://dash.cloudflare.com/?to=/:account/r2/overview"
step "Create a private bucket named prosepect."
step "Open Manage R2 API Tokens and create an Object Read & Write token restricted to that bucket."
ask S3_BUCKET "R2 bucket name [prosepect]:"
S3_BUCKET="${S3_BUCKET:-prosepect}"
ask S3_ENDPOINT "R2 S3 endpoint, such as https://ACCOUNT_ID.r2.cloudflarestorage.com:"
ask_secret S3_ACCESS_KEY_ID "R2 Access Key ID:"
ask_secret S3_SECRET_ACCESS_KEY "R2 Secret Access Key:"
write_env S3_BUCKET "$S3_BUCKET"
write_env S3_REGION "auto"
write_env S3_ENDPOINT "$S3_ENDPOINT"
write_env S3_PUBLIC_ENDPOINT "$S3_ENDPOINT"
write_env S3_ACCESS_KEY_ID "$S3_ACCESS_KEY_ID"
write_env S3_SECRET_ACCESS_KEY "$S3_SECRET_ACCESS_KEY"
write_env S3_ALLOW_HTTP "false"
write_env S3_VIRTUAL_HOSTED_STYLE "false"
chmod 600 "$ENV_FILE"

stage "Google OAuth and Calendar"
say "Create one Google OAuth web client for login and incremental Calendar consent."
open_url "https://console.cloud.google.com/apis/library/calendar-json.googleapis.com?project=${GCP_PROJECT_ID}"
step "Enable the Google Calendar API."
open_url "https://console.cloud.google.com/auth/overview?project=${GCP_PROJECT_ID}"
step "Configure the OAuth consent screen. Add your Google account as a test user if the app remains in testing."
open_url "https://console.cloud.google.com/auth/clients?project=${GCP_PROJECT_ID}"
step "Create a Web application client named Prosepect."
step "Add https://prosepect.com as an authorized JavaScript origin."
step "Add https://api.prosepect.com/api/v1/auth/google/callback as an authorized redirect URI."
ask GOOGLE_CLIENT_ID "Google OAuth Client ID:"
ask_secret GOOGLE_CLIENT_SECRET "Google OAuth Client Secret:"
TOKEN_ENCRYPTION_KEY=$(_existing TOKEN_ENCRYPTION_KEY || true)
if [[ -z "$TOKEN_ENCRYPTION_KEY" ]]; then
  TOKEN_ENCRYPTION_KEY=$(openssl rand -base64 32)
fi
ask INVITE_EMAIL "Google account email to invite:"
write_env GOOGLE_CLIENT_ID "$GOOGLE_CLIENT_ID"
write_env GOOGLE_CLIENT_SECRET "$GOOGLE_CLIENT_SECRET"
write_env GOOGLE_REDIRECT_URI "https://api.prosepect.com/api/v1/auth/google/callback"
write_env TOKEN_ENCRYPTION_KEY "$TOKEN_ENCRYPTION_KEY"
write_env INVITE_EMAIL "$INVITE_EMAIL"
chmod 600 "$ENV_FILE"

stage "Google Cloud resources and secrets"
say "This creates the artifact repository, service accounts, and five secret values."
confirm "Create Google Cloud resources in ${GCP_PROJECT_ID}?" || exit 1
gcloud services enable \
  artifactregistry.googleapis.com \
  cloudbuild.googleapis.com \
  run.googleapis.com \
  cloudscheduler.googleapis.com \
  secretmanager.googleapis.com \
  --project "$GCP_PROJECT_ID"
if ! gcloud artifacts repositories describe prosepect \
  --project "$GCP_PROJECT_ID" --location "$GCP_REGION" >/dev/null 2>&1; then
  gcloud artifacts repositories create prosepect \
    --project "$GCP_PROJECT_ID" --location "$GCP_REGION" \
    --repository-format docker --description "Prosepect release images"
fi
for account in prosepect-runtime prosepect-scheduler; do
  if ! gcloud iam service-accounts describe \
    "${account}@${GCP_PROJECT_ID}.iam.gserviceaccount.com" \
    --project "$GCP_PROJECT_ID" >/dev/null 2>&1; then
    gcloud iam service-accounts create "$account" \
      --project "$GCP_PROJECT_ID" --display-name "$account"
  fi
done
upsert_google_secret prosepect-database-url "$DATABASE_URL"
upsert_google_secret prosepect-google-client-secret "$GOOGLE_CLIENT_SECRET"
upsert_google_secret prosepect-token-encryption-key "$TOKEN_ENCRYPTION_KEY"
upsert_google_secret prosepect-s3-access-key-id "$S3_ACCESS_KEY_ID"
upsert_google_secret prosepect-s3-secret-access-key "$S3_SECRET_ACCESS_KEY"

stage "Build and deploy the API"
if [[ -n "$(git status --porcelain)" ]]; then
  warn "The repository is not clean. Deploy only the reviewed commit pushed to GitHub."
  confirm "Build the current working tree anyway?" || exit 1
fi
GIT_REVISION=$(git rev-parse --short HEAD)
GCP_IMAGE="${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/prosepect/prosepect:${GIT_REVISION}"
write_env GCP_IMAGE "$GCP_IMAGE"
confirm "Build and deploy image ${GCP_IMAGE}?" || exit 1
gcloud builds submit . \
  --project "$GCP_PROJECT_ID" \
  --region "$GCP_REGION" \
  --config deploy/gcp/cloudbuild.yaml \
  --substitutions "_IMAGE=${GCP_IMAGE}"
PUBLIC_ENV="APP_ENV=production,BIND_ADDRESS=0.0.0.0:3000,DATABASE_MAX_CONNECTIONS=5,APP_URL=https://prosepect.com,CORS_ALLOWED_ORIGIN=https://prosepect.com,ALLOW_INSECURE_DEV_AUTH=false,INVITE_ONLY=true,TRUST_PROXY_HEADERS=true,GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID},GOOGLE_REDIRECT_URI=https://api.prosepect.com/api/v1/auth/google/callback,S3_BUCKET=${S3_BUCKET},S3_REGION=auto,S3_ENDPOINT=${S3_ENDPOINT},S3_PUBLIC_ENDPOINT=${S3_ENDPOINT},S3_ALLOW_HTTP=false,S3_VIRTUAL_HOSTED_STYLE=false,MAX_FILE_SIZE_BYTES=26214400"
SECRET_ENV="DATABASE_URL=prosepect-database-url:latest,GOOGLE_CLIENT_SECRET=prosepect-google-client-secret:latest,TOKEN_ENCRYPTION_KEY=prosepect-token-encryption-key:latest,S3_ACCESS_KEY_ID=prosepect-s3-access-key-id:latest,S3_SECRET_ACCESS_KEY=prosepect-s3-secret-access-key:latest"
gcloud run deploy prosepect-api \
  --project "$GCP_PROJECT_ID" --region "$GCP_REGION" \
  --image "$GCP_IMAGE" --service-account "prosepect-runtime@${GCP_PROJECT_ID}.iam.gserviceaccount.com" \
  --allow-unauthenticated --port 3000 --cpu 1 --memory 512Mi \
  --concurrency 40 --max-instances 1 --min-instances 0 --timeout 60 \
  --set-env-vars "$PUBLIC_ENV" --set-secrets "$SECRET_ENV"

stage "Deploy and schedule the worker"
say "The one-shot worker runs every 15 minutes to stay within the free compute allowance."
gcloud run jobs deploy prosepect-worker \
  --project "$GCP_PROJECT_ID" --region "$GCP_REGION" \
  --image "$GCP_IMAGE" --service-account "prosepect-runtime@${GCP_PROJECT_ID}.iam.gserviceaccount.com" \
  --command prosepect-worker --args=--once --tasks 1 --max-retries 2 \
  --task-timeout 5m --cpu 1 --memory 512Mi \
  --set-env-vars "$PUBLIC_ENV" --set-secrets "$SECRET_ENV"
gcloud run jobs add-iam-policy-binding prosepect-worker \
  --project "$GCP_PROJECT_ID" --region "$GCP_REGION" \
  --member "serviceAccount:prosepect-scheduler@${GCP_PROJECT_ID}.iam.gserviceaccount.com" \
  --role roles/run.invoker >/dev/null
SCHEDULER_URI="https://run.googleapis.com/v2/projects/${GCP_PROJECT_ID}/locations/${GCP_REGION}/jobs/prosepect-worker:run"
if gcloud scheduler jobs describe prosepect-worker \
  --project "$GCP_PROJECT_ID" --location "$GCP_REGION" >/dev/null 2>&1; then
  gcloud scheduler jobs update http prosepect-worker \
    --project "$GCP_PROJECT_ID" --location "$GCP_REGION" \
    --schedule "*/15 * * * *" --time-zone Etc/UTC \
    --uri "$SCHEDULER_URI" --http-method POST \
    --oauth-service-account-email "prosepect-scheduler@${GCP_PROJECT_ID}.iam.gserviceaccount.com" \
    --oauth-token-scope "https://www.googleapis.com/auth/cloud-platform"
else
  gcloud scheduler jobs create http prosepect-worker \
    --project "$GCP_PROJECT_ID" --location "$GCP_REGION" \
    --schedule "*/15 * * * *" --time-zone Etc/UTC \
    --uri "$SCHEDULER_URI" --http-method POST \
    --oauth-service-account-email "prosepect-scheduler@${GCP_PROJECT_ID}.iam.gserviceaccount.com" \
    --oauth-token-scope "https://www.googleapis.com/auth/cloud-platform"
fi
gcloud run jobs execute prosepect-worker \
  --project "$GCP_PROJECT_ID" --region "$GCP_REGION" --wait

stage "Domains and Vercel"
say "Map api.prosepect.com to Cloud Run, then deploy the SPA at prosepect.com."
if ! gcloud beta run domain-mappings describe \
  --project "$GCP_PROJECT_ID" --region "$GCP_REGION" \
  --domain api.prosepect.com >/dev/null 2>&1; then
  if ! gcloud beta run domain-mappings create \
    --project "$GCP_PROJECT_ID" --region "$GCP_REGION" \
    --service prosepect-api --domain api.prosepect.com; then
    warn "Google may require domain ownership verification before creating the mapping."
    open_url "https://search.google.com/search-console/welcome"
    step "Verify prosepect.com, then retry this stage by rerunning the wizard."
    exit 1
  fi
fi
gcloud beta run domain-mappings describe \
  --project "$GCP_PROJECT_ID" --region "$GCP_REGION" \
  --domain api.prosepect.com --format='yaml(status.resourceRecords)'
step "Add the displayed api.prosepect.com DNS record at your DNS provider."
open_url "https://vercel.com/new/clone?repository-url=https://github.com/danarrigo/prosepect"
step "Import the repository with apps/web as Root Directory and enable including files outside the root."
step "Set VITE_API_URL to https://api.prosepect.com for Production."
step "Deploy, attach prosepect.com, and add the DNS records Vercel displays."
pause "Press Enter when Vercel and both DNS records are configured."

stage "Invite and verify"
say "The API migration creates the invite table before the first sign-in."
API_READY="https://api.prosepect.com/ready"
for attempt in $(seq 1 40); do
  if curl --fail --silent "$API_READY" >/dev/null; then
    break
  fi
  sleep 15
done
curl --fail --silent "$API_READY" >/dev/null
if require_command psql; then
  psql "$DATABASE_URL" --set ON_ERROR_STOP=1 --set invite_email="$INVITE_EMAIL" <<'SQL'
INSERT INTO account_invites (id, email)
VALUES (gen_random_uuid(), LOWER(:'invite_email'))
ON CONFLICT (email) DO NOTHING;
SQL
else
  warn "psql is unavailable. Add the invite through the Neon SQL editor."
fi
open_url "https://prosepect.com"
step "Sign in with ${INVITE_EMAIL}."
step "Create a task and event, upload and download an attachment, then connect Google Calendar."
step "Check Cloud Run API logs and the latest prosepect-worker execution for errors."
pause "Press Enter after the production smoke test passes."

finish
